FROM microsoft/dotnet:2.2-sdk as build

ARG BUILDCONFIG=RELEASE
ARG VERSION=1.0.0

COPY ProjectArcher_Backend.csproj /build/

RUN dotnet restore ./build/ProjectArcher_Backend.csproj 

COPY . ./build/
WORKDIR /build/
RUN dotnet publish ./ProjectArcher_Backend.csproj  -c $BUILDCONFIG -o out /p:Version=$VERSION

FROM microsoft/dotnet:2.2-aspnetcore-runtime
WORKDIR /app

COPY --from=build /build/out .

ENTRYPOINT ["dotnet", "ProjectArcher_Backend.dll"]